Added string filtering for "madrich"
pinkasey/etgar22extension pull request #2
Opened 2017-02-28 23:32 UTC by alongalky

2017-03-01 11:54 UTC, pinkasey requested changes

2017-03-01 11:54 UTC, pinkasey commented on scripts/facebook-scanner.js
> +      'מדריך',
'[מדריך]',
'[מדריכה]',
'[מדריכ/ה]',
'[מדריך/ה]',
[Mentor]'

Case insensitive

2017-03-01 11:56 UTC, pinkasey commented
Thanks for the contribution!
Please see my comment.
If you dont have time to make that change - i'll accept this PR and do it myself later.

2017-03-01 12:14 UTC, alongalky commented
If you're eager you can go ahead, if not I'll probably get to it in the next few days

2017-03-01 12:25 UTC, pinkasey commented
Thanks ☺
No rush

2017-03-06 12:24 UTC, pinkasey approved these changes

2017-03-06 12:24 UTC, merged